# All variables can be overwritten by name=value pairs as arguments to nmake,
# e.g. by running
# 	?> nmake SPECSHARPROOT=c:\checkout\SpecSharp

SPECSHARPROOT = d:\SpecSharpCodePlex\SpecSharp
# Use the first one if you want to build Boogie using the LKG build of Spec#.
# Use the second one if you want to build Boogie using a freshly built version of Spec#.
#
#SPECSHARPBINDIR = Microsoft.SpecSharp\LastKnownGood9
SPECSHARPBINDIR = Microsoft.SpecSharp\Registration

all: 
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\ITaskManager.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\ITaskManager.pdb"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Compiler.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Compiler.pdb"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Compiler.Framework.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Compiler.Framework.pdb"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Compiler.Runtime.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Compiler.Runtime.pdb"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Microsoft.SpecSharp.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Microsoft.SpecSharp.pdb"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Microsoft.SpecSharp.Runtime.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Microsoft.SpecSharp.Runtime.pdb"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Mscorlib.Contracts.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Contracts.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Xml.Contracts.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Compiler.Contracts.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\System.Compiler.Framework.Contracts.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Microsoft.VisualStudio.IntegrationHelper.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Microsoft.VisualStudio.IntegrationHelper.pdb"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Microsoft.VisualStudio.Package.dll"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\Microsoft.VisualStudio.Package.pdb"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\ssc.exe"
	copy /y "$(SPECSHARPROOT)\$(SPECSHARPBINDIR)\ssc.pdb"
